// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma
import fs from 'fs';
import path from 'path';
import { defineConfig } from "prisma/config";

function readDatabaseUrlFromEnvFile(): string | undefined {
  const envFilePath = path.join(process.cwd(), '.env.local');

  if (!fs.existsSync(envFilePath)) {
    return undefined;
  }

  const content = fs.readFileSync(envFilePath, 'utf8');
  const match = content.match(/^DATABASE_URL=(.*)$/m);

  if (!match) {
    return undefined;
  }

  const rawValue = match[1].trim();

  if ((rawValue.startsWith('"') && rawValue.endsWith('"')) || (rawValue.startsWith("'") && rawValue.endsWith("'"))) {
    return rawValue.slice(1, -1);
  }

  return rawValue;
}

function getDatasourceUrl(): string {
  return process.env.DATABASE_URL ?? readDatabaseUrlFromEnvFile() ?? 'file:./prisma/dev.db';
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatasourceUrl(),
  },
});
